linters-settings:
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/stretchr/testify/require
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify
